[build]
  publish = "."
  functions = "netlify/functions"

# Optimizer
[[redirects]]
  from = "/optimizer"
  to = "/index-v10.html"
  status = 200

# Builder
[[redirects]]
  from = "/builder"
  to = "/builder.html"
  status = 200
